### ISSUE TITLE
Feedback about teams protocol

### ISSUE THREAD

**Issue by PabRod** [Team-Nabla/.github#10]
Please leave your feedback for the OR [here](https://nlesc.sharepoint.com/:w:/s/teamnabla2/Eb-y3Ii1CmxHq1kowvzCu6gBij_g4MmcM7fVTZYlFeSOUw?e=6t2Qjl).

## Done

- [ ] Aron
- [ ] Murilo
- [ ] Luisa
- [ ] Simone
- [ ] Pablo R.

**Comment by luisaforozco** [comment]
Hello all, I see that no one has added any feedback. Does anyone still want to write something or are we content with the situation and don't want to give any feedback on this matter?

**Comment by APJansen** [comment]
Hi Luisa, sorry about that, as far as I'm concerned it's as you say, things turned out ok in the end, and the main issue for me (not being informed or consulted on decisions affecting us) I think has been understood by all involved, and has improved. So I would say that indeed, unless it's explicitly asked of us, I think there's no need to stir things up again.

**Comment by luisaforozco** [comment]
Thanks for the clarification!
