### ISSUE TITLE
Try GitHub projects, and give feedback

### ISSUE THREAD

**Issue by PabRod** [Team-Nabla/.github#12]
## Description

GitHub projects look like a very good candidate tool for our team task management but... is it? The only way to know is to give it a try!

## Action points

I invite you to give it a try for a couple of weeks.

Please use this issue for:

- Feedback
- Questions
- Comments
- etc

**Comment by SCiarella** [comment]
I like this!

However, I can see this thread only in the 'issues' window, and not the 'projects' ones, where I usually store my kanban boards.
Also, I think it will be extremely useful to have github projects within the specific organizations, in order to address specific project-related issued and set up kanban boards.

**Comment by PabRod** [comment]
Thanks for your enthousiastic feedback, @SCiarella.

> I can see this thread only in the 'issues' window, and not the 'projects' ones

In my opinion this is a feature, not a bug. All project items are issues, and the details can (should?) be accessed via the issues view.

> I think it will be extremely useful to have github projects within the specific organizations, in order to address specific project-related issued and set up kanban boards.

This is indeed the idea. Each project will have its own projects panel.

**Comment by PabRod** [comment]
I think we can consider this closed.
